# Production Prometheus configuration for ensimu-space
# Monitoring and metrics collection

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'ensimu-production'
    replica: '1'

rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # EnsumuSpace Backend API
  - job_name: 'ensimu-backend'
    static_configs:
      - targets: ['backend:8001']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # EnsumuSpace Frontend
  - job_name: 'ensimu-frontend'
    static_configs:
      - targets: ['frontend:80']
    metrics_path: '/health'
    scrape_interval: 30s
    scrape_timeout: 10s

  # PostgreSQL Database (with postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis Cache (with redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    scrape_timeout: 10s

  # HAProxy Load Balancer
  - job_name: 'haproxy'
    static_configs:
      - targets: ['haproxy:8404']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Nginx Reverse Proxy
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # System metrics (node_exporter)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Docker metrics (cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 60s
    scrape_timeout: 10s

  # Loki log aggregator
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
    metrics_path: '/metrics'
    scrape_interval: 60s
    scrape_timeout: 10s

  # Custom application metrics
  - job_name: 'ensimu-workflows'
    static_configs:
      - targets: ['backend:8001']
    metrics_path: '/workflow/metrics'
    scrape_interval: 60s
    scrape_timeout: 15s

  # Auto-scaler metrics
  - job_name: 'autoscaler'
    static_configs:
      - targets: ['autoscaler:8080']
    metrics_path: '/metrics'
    scrape_interval: 60s
    scrape_timeout: 10s

# Remote write configuration (for external monitoring systems)
# remote_write:
#   - url: "https://prometheus-remote.example.com/api/v1/write"
#     headers:
#       Authorization: "Bearer YOUR_TOKEN_HERE"

# Remote read configuration (for external monitoring systems)
# remote_read:
#   - url: "https://prometheus-remote.example.com/api/v1/read"
#     headers:
#       Authorization: "Bearer YOUR_TOKEN_HERE"

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true